-- AlterTable
ALTER TABLE "weather_score" ALTER COLUMN "aqi_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "pm25_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "pm10_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "temperature_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "humidity_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "rain_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "uv_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "wind_score" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "comfort_score" SET DATA TYPE DECIMAL(4,2);
